[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["홍민형 <mh.hong@woowahan.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.0"
